[package]
name = "sapphire"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[[bin]]
name = "sapphire"
path = "src/cli.rs"

[dependencies]
fnv = "1.0"
parking_lot = "0.7"
sapphire-parser = { path = "parser" }
smallvec = "0.6"

[workspace]
