[package]
name = "sapphire-compiler-macro"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
sapphire-compiler = { path = "../compiler" }
syn = "0.15"
