[package]
name = "sapphire-parser-gen"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
petgraph = "0.4"
proc-macro2 = "0.4"
quote = "0.6"
